[workspace]
resolver = "3"
members = [
    "pve-api-types",
]

[workspace.package]
authors = [ "Proxmox Support Team <support@proxmox.com>" ]
edition = "2024"
license = "AGPL-3"
repository = "git://git.proxmox.com/git/proxmox-api-types.git"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
hex = "0.4.3"
openssl = "0.10.45"
percent-encoding = "2.1"
regex = "1.7"
serde = "1"
serde_plain = "1"
serde_json = "1"

proxmox-api-macro = "1.3"
proxmox-serde = { version = "1", features = ["perl"] }
proxmox-schema = "5"

proxmox-client = "1"
proxmox-http = "0.9"
