[workspace]
resolver = "2"
members = [
    "pve-api-types",
]

[workspace.package]
authors = [ "Proxmox Support Team <support@proxmox.com>" ]
edition = "2021"
license = "AGPL-3"
repository = "git://git.proxmox.com/git/proxmox-api-types.git"

[workspace.dependencies]
anyhow = "1"
hex = "0.4.3"
openssl = "0.10.45"
percent-encoding = "2.1"
regex = "1.7"
serde = "1"
serde_plain = "1"
serde_json = "1"

proxmox-login = "0.1.1"
proxmox-schema = "3"

proxmox-client = "0.5"
proxmox-http = "0.9"
