[package]
name = "proxmox-network-api"
description = "Network Management API implementation"
version = "0.1.5"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
const_format.workspace = true
regex.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
nix = { workspace = true, optional = true }
libc = { workspace = true, optional = true }

proxmox-sys = { workspace = true, optional = true }
proxmox-schema = { workspace = true, features = ["api-macro", "api-types"] }
proxmox-config-digest = { workspace = true, optional = true }
proxmox-product-config = { workspace = true, optional = true }
proxmox-ve-config = "0.2.3"

[features]
default = []
impl = [
    "dep:proxmox-config-digest",
    "proxmox-config-digest?/openssl",
    "dep:proxmox-product-config",
    "dep:nix",
    "dep:libc",
    "dep:proxmox-sys",
]
