//! Safe wrappers around systemd's `sd-id128` 128-bit ID APIs.
//!
//! `sd-id128.h` is part of `libsystemd` and provides APIs to generate, convert, and compare
//! 128-bit ID values, which are a generalization of RFC 4122 OSF UUIDs with a simpler string
//! format. See `sd-id128(3)` for the full C API.
//!
//! See [`get_app_specific_id`] for deriving a stable, application-specific ID from the local
//! machine ID (`sd_id128_get_machine_app_specific(3)`, `machine-id(5)`), and [`SystemdId128Error`]
//! for the errors it can return.

use std::fmt;

use crate::sys::{self, sd_id128_t};

/// Errors that can occur when deriving an application-specific ID from the local machine ID.
///
/// See `sd_id128_get_machine_app_specific(3)` and `sd-id128(3)` for background on the underlying
/// systemd API.
#[derive(Debug, PartialEq, Eq)]
pub enum SystemdId128Error {
    /// The supplied application ID is not a valid `sd_id128_t` value.
    ///
    /// Currently this is returned when `app_id` consists entirely of zero bytes, which systemd
    /// treats as the "null" ID. A valid application ID should be generated once per application
    /// (for example with `systemd-id128 new`) and then hard-coded into the program.
    InvalidAppId,
    /// systemd was unable to derive an application-specific ID from the local machine ID.
    ///
    /// This typically means that no machine ID is available on the system, e.g. `/etc/machine-id`
    /// is missing, empty, or otherwise unreadable. See `machine-id(5)` for details on how the
    /// machine ID is provisioned.
    GenerationError,
}

impl std::error::Error for SystemdId128Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        None
    }
}

impl fmt::Display for SystemdId128Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SystemdId128Error::InvalidAppId => f.write_str("Provided application ID is invalid."),
            SystemdId128Error::GenerationError => {
                f.write_str("Failed to generate machine-id based on application ID.")
            }
        }
    }
}

/// Derives a stable, application-specific 128-bit ID from the local machine ID.
///
/// This is a safe Rust wrapper around systemd's `sd_id128_get_machine_app_specific(3)`.
/// It combines the host's machine ID (as exposed by `sd_id128_get_machine(3)` and documented in
/// `machine-id(5)`) with the caller-supplied `app_id` via an HMAC-based construction, and returns
/// the resulting 128-bit value.
///
/// Properties of the returned ID, as guaranteed by the underlying systemd API:
///
/// - **Stable**: repeated calls on the same machine with the same `app_id` always yield the
///   same value, so the ID may be persisted and compared across reboots.
/// - **Per-machine**: the same `app_id` evaluated on a different machine produces a different,
///   unrelated value; the machine ID cannot be recovered from the result.
/// - **Per-application**: different `app_id` values on the same machine produce unrelated
///   values, so IDs generated by different applications cannot be correlated without knowing
///   each application's `app_id`.
///
/// This makes the function suitable whenever an application needs a per-installation identifier
/// without leaking the machine ID itself.
///
/// # Arguments
///
/// * `app_id` - A 16-byte `sd_id128_t` value identifying the application. It must not be all
///   zeros. Per the systemd documentation, this value should be generated once (for example
///   with `systemd-id128 new`) and then compiled into the application as a constant.
///
/// # Errors
///
/// * [`SystemdId128Error::InvalidAppId`] if `app_id` is the null ID (all zero bytes).
/// * [`SystemdId128Error::GenerationError`] if systemd could not derive an ID, which generally
///   indicates that no machine ID is available on the running system.
pub fn get_app_specific_id(app_id: [u8; 16]) -> Result<[u8; 16], SystemdId128Error> {
    let mut res = sd_id128_t { bytes: [0; 16] };

    if app_id.iter().all(|b| *b == 0) {
        return Err(SystemdId128Error::InvalidAppId);
    }
    unsafe {
        sys::sd_id128_get_machine_app_specific(sd_id128_t { bytes: app_id }, &mut res);
    }
    if res.bytes.iter().all(|b| *b == 0) {
        return Err(SystemdId128Error::GenerationError);
    }
    Ok(res.bytes)
}

#[test]
fn test_invalid_app_id() {
    let invalid = [0; 16];
    let res = get_app_specific_id(invalid);
    assert!(res.is_err());
    assert_eq!(res, Err(SystemdId128Error::InvalidAppId));
}

#[test]
fn test_valid_app_id() {
    // no machine-id, no app-specific ID either..
    if !std::path::Path::new("/etc/machine-id").exists() {
        return;
    }

    // UUID generated with `systemd-id128 new` and converted from hex
    let valid = 950247666410175165299169499632875718_u128.to_le_bytes();

    let res = get_app_specific_id(valid);
    assert!(res.is_ok());

    let res2 = get_app_specific_id(valid);
    assert!(res2.is_ok());

    // cannot verify the expected result, since that depends on the machine the test runs on
    // we can verify that two generations using the same machine and app-id give identical results
    assert_eq!(res, res2);
}
