[package]
name = "proxmox-time-api"
version = "1.0.1"
description = "Time Management API implementation"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }

proxmox-sys = { workspace = true, optional = true }
proxmox-schema = { workspace = true, features = ["api-macro", "api-types"] }
proxmox-time = { workspace = true, optional = true }
proxmox-product-config = { workspace = true, optional = true }

[features]
default = []
impl = [
    "dep:proxmox-product-config",
    "dep:proxmox-sys",
    "dep:proxmox-time",
]
