[package]
name = "proxmox-rrd-api-types"
description = "Types for RRD values."
version = "1.1.1"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_plain.workspace = true

proxmox-schema = { workspace = true, features = [ "api-macro" ] }
